In [90]:
import pandas as pd
import matplotlib.pyplot as plt
import csv
import os

In [91]:
#*****CHANGE THE NAME OF THE IN AND OUT FILES****
#Load the first report to extract the headers
first_report = pd.read_csv("CAT1_CAT2_01012007_31122010.csv", encoding = 'raw_unicode_escape', low_memory = False)

In [92]:
first_report.head(10)

,enquiry_number,job_number,enquiry_time,service_code,subject_code,subject_name,priority_code,enq_status_code,log_effective_date,enquiry_desc,...,claim_date,claim_tot,claim_code,area_name,site_address,quad,feature_location,asset_id,Unnamed: 20,Unnamed: 21
0,1558145,946775,05/05/2010 09:16,CW,PH1,Urgent Pothole 24 Hr Repair,H24,430,07/05/2010 11:45,just along from the county border approx 20 ya...,...,17/05/2010 09:30,41.67,F1/946775,Tring Town,A41 Tring Bypass,SW,County boundary to B4635 overbridge,A41/011,NaN,NaN
1,1533019,922316,09/02/2010 15:23,WM,RICE,Ice And Snow On Road,H2,400,20/12/2009 12:55,OOH 20096 - CARERS NEED ACCESS TO ELDERLY AND ...,...,17/02/2010 09:13,192.29,F1/922316,Kings Langley,Abbots Rise,SW,Hempstead Road to house 59,2U415/10,NaN,NaN
2,1532872,922185,09/02/2010 11:54,WM,RICE,Ice And Snow On Road,H2,400,20/12/2009 10:10,OOH 20076 - CARERS NEED ACCESS TO ELDERLY AND ...,...,17/02/2010 08:59,195.24,F1/922185,Kings Langley,Abbots Rise,SW,Hempstead Road to house 59,2U415/10,NaN,NaN
3,1350964,646550,05/02/2008 16:41,CW,CPTH,Pothole In Road,NaN,400,06/02/2008 12:00,The road was repaired at the jucntion of the A...,...,NaN,NaN,NaN,Kings Langley,Abbots Rise,EH,Hempstead Road to house 59,2U415/10,NaN,NaN
4,1377901,701625,10/07/2008 12:00,CW,CPTH,Pothole In Road,NaN,410,10/07/2008 14:40,Road surface is breaking up on section of road...,...,NaN,NaN,NaN,Kings Langley,Abbots Rise,WEB,Hempstead Road to house 59,2U415/10,NaN,NaN
5,1405136,758766,22/12/2008 10:25,CW,PH7,Pothole 7 Dy Permanent Repair,D7,430,23/12/2008 10:45,ABBOTS RISE-KINGS LANGLEY. there is a pothole ...,...,NaN,NaN,NaN,Kings Langley,Abbots Rise,EH,Hempstead Road to house 59,2U415/10,NaN,NaN
6,1375368,696124,23/06/2008 16:21,CW,CPTH,Pothole In Road,NaN,420,24/06/2008 14:35,there are several holes and this is on the ben...,...,NaN,NaN,NaN,Kings Langley,Abbots Rise,EH,Hempstead Road to house 59,2U415/10,NaN,NaN
7,1310494,576470,20/06/2007 11:30,FL,PDAM,Property Damaged By Flooding,H2,440,20/06/2007 11:45,Drain outside property has flooded causing flo...,...,NaN,NaN,NaN,Kings Langley,Abbots Rise,EH,Hempstead Road to house 59,2U415/10,NaN,NaN
8,1277895,513495,18/01/2007 15:24,CW,CPTH,Pothole In Road,NaN,400,19/01/2007 14:00,the road has potholes,...,NaN,NaN,NaN,Kings Langley,Abbots Rise,EH,Hempstead Road to house 59,2U415/10,NaN,NaN
9,1315533,584857,20/07/2007 13:03,FL,CFL,Hazardous carriageway flood,H2,400,20/07/2007 15:03,CARRIAGEWAY FLOODED and water is flooding into...,...,NaN,NaN,NaN,Kings Langley,Abbots Rise,EH,Hempstead Road to house 59,2U415/10,NaN,NaN

In [93]:
csv_header_tup = ''
i = 0
for col in first_report.columns: 
    if i == 0:
        csv_header_tup = str(col)
        i=i+1
    else:
        csv_header_tup = csv_header_tup + "," + str(col)

In [94]:
csv_header_tup

'enquiry_number,job_number,enquiry_time,service_code,subject_code,subject_name,priority_code,enq_status_code,log_effective_date,enquiry_desc,officer_code,enq_status_name,claim_date,claim_tot,claim_code,area_name,site_address,quad,feature_location,asset_id,Unnamed: 20,Unnamed: 21'

In [95]:
csv_header= ''.join((csv_header_tup))

In [78]:
#csv_header_tup= 'Outstation', 'DateTime','Ground1','Ground2','Ground3','Ground4','Dew Temp','Air Temp','Deep','Deep2','Wind Speed','Condition1','Condition2','Condition3','Condition4','St1','St2','St3','St4','Rel Humidity','Precip','Rain','WDC','WDR','Wind Gust','Volts','Film','Salt Condn','Fault','Visibility'
#csv_header= ','.join((csv_header_tup))

In [96]:
csv_header

'enquiry_number,job_number,enquiry_time,service_code,subject_code,subject_name,priority_code,enq_status_code,log_effective_date,enquiry_desc,officer_code,enq_status_name,claim_date,claim_tot,claim_code,area_name,site_address,quad,feature_location,asset_id,Unnamed: 20,Unnamed: 21'

In [97]:
csv_out = 'defects_consolidated4.csv'

csv_dir = os.getcwd()

dir_tree = os.walk(csv_dir)
for dirpath, dirnames, filenames in dir_tree:
   pass

csv_list = []
for file in filenames:
   if file.endswith('.csv'):
      csv_list.append(file)

print(csv_dir)

C:\Users\J FernandezGomez\Jupyter Notebooks\Cleaning_Data_Notebooks\2_Defects

In [98]:
print(csv_list)

['CAT1_CAT2_01012007_31122010.csv', 'CAT1_CAT2_01012011_31122014.csv', 'CAT1_CAT2_01012015_31122018.csv', 'CAT1_CAT2_01012019_22072019.csv']

In [99]:
csv_merge = open(csv_out, 'w', encoding = 'raw_unicode_escape')
csv_merge.write(csv_header)
csv_merge.write('\n')

1

In [100]:
if csv_merge.closed:
  print("Forking file is closed now")
for file in csv_list:
   csv_in = open(file, encoding = 'raw_unicode_escape', errors = 'ignore')
   for line in csv_in:
      if line.startswith(csv_header):
         continue
      if csv_merge.closed:
         print("Forking file is closed")
      else:
         csv_merge.write(line)
   csv_in.close()
csv_merge.close()
print('Verify consolidated CSV file : ' + csv_out)

Verify consolidated CSV file : defects_consolidated4.csv

In [101]:
#Load the consolidated dataframe and check its size to validate
df = pd.read_csv("defects_consolidated4.csv", encoding = 'raw_unicode_escape')
df.shape

(1114185, 22)

In [102]:
#Review a sample of the data to confirm
df.head(5)

,enquiry_number,job_number,enquiry_time,service_code,subject_code,subject_name,priority_code,enq_status_code,log_effective_date,enquiry_desc,...,claim_date,claim_tot,claim_code,area_name,site_address,quad,feature_location,asset_id,Unnamed: 20,Unnamed: 21
0,enquiry_number,job_number,enquiry_time,service_code,subject_code,subject_name,priority_code,enq_status_code,log_effective_date,enquiry_desc,...,claim_date,claim_tot,claim_code,area_name,site_address,quad,feature_location,asset_id,NaN,NaN
1,1558145,946775,05/05/2010 09:16,CW,PH1,Urgent Pothole 24 Hr Repair,H24,430,07/05/2010 11:45,just along from the county border approx 20 ya...,...,17/05/2010 09:30,41.67,F1/946775,Tring Town,A41 Tring Bypass,SW,County boundary to B4635 overbridge,A41/011,NaN,NaN
2,1533019,922316,09/02/2010 15:23,WM,RICE,Ice And Snow On Road,H2,400,20/12/2009 12:55,OOH 20096 - CARERS NEED ACCESS TO ELDERLY AND ...,...,17/02/2010 09:13,192.29,F1/922316,Kings Langley,Abbots Rise,SW,Hempstead Road to house 59,2U415/10,NaN,NaN
3,1532872,922185,09/02/2010 11:54,WM,RICE,Ice And Snow On Road,H2,400,20/12/2009 10:10,OOH 20076 - CARERS NEED ACCESS TO ELDERLY AND ...,...,17/02/2010 08:59,195.24,F1/922185,Kings Langley,Abbots Rise,SW,Hempstead Road to house 59,2U415/10,NaN,NaN
4,1350964,646550,05/02/2008 16:41,CW,CPTH,Pothole In Road,NaN,400,06/02/2008 12:00,The road was repaired at the jucntion of the A...,...,NaN,NaN,NaN,Kings Langley,Abbots Rise,EH,Hempstead Road to house 59,2U415/10,NaN,NaN

In [103]:
df.columns

Index(['enquiry_number', 'job_number', 'enquiry_time', 'service_code',
       'subject_code', 'subject_name', 'priority_code', 'enq_status_code',
       'log_effective_date', 'enquiry_desc', 'officer_code', 'enq_status_name',
       'claim_date', 'claim_tot', 'claim_code', 'area_name', 'site_address',
       'quad', 'feature_location', 'asset_id', 'Unnamed: 20', 'Unnamed: 21'],
      dtype='object')

In [105]:
df.drop(columns = ['Unnamed: 20','Unnamed: 21'], inplace = True )

In [106]:
df.columns

Index(['enquiry_number', 'job_number', 'enquiry_time', 'service_code',
       'subject_code', 'subject_name', 'priority_code', 'enq_status_code',
       'log_effective_date', 'enquiry_desc', 'officer_code', 'enq_status_name',
       'claim_date', 'claim_tot', 'claim_code', 'area_name', 'site_address',
       'quad', 'feature_location', 'asset_id'],
      dtype='object')

In [108]:
df.drop(0, inplace = True)

In [109]:
df.head(5)

,enquiry_number,job_number,enquiry_time,service_code,subject_code,subject_name,priority_code,enq_status_code,log_effective_date,enquiry_desc,officer_code,enq_status_name,claim_date,claim_tot,claim_code,area_name,site_address,quad,feature_location,asset_id
1,1558145,946775,05/05/2010 09:16,CW,PH1,Urgent Pothole 24 Hr Repair,H24,430,07/05/2010 11:45,just along from the county border approx 20 ya...,LW2,0430-Ref'd to 3rd Party by HCC,17/05/2010 09:30,41.67,F1/946775,Tring Town,A41 Tring Bypass,SW,County boundary to B4635 overbridge,A41/011
2,1533019,922316,09/02/2010 15:23,WM,RICE,Ice And Snow On Road,H2,400,20/12/2009 12:55,OOH 20096 - CARERS NEED ACCESS TO ELDERLY AND ...,ECR2,0400-Repaired/Replaced,17/02/2010 09:13,192.29,F1/922316,Kings Langley,Abbots Rise,SW,Hempstead Road to house 59,2U415/10
3,1532872,922185,09/02/2010 11:54,WM,RICE,Ice And Snow On Road,H2,400,20/12/2009 10:10,OOH 20076 - CARERS NEED ACCESS TO ELDERLY AND ...,ECR2,0400-Repaired/Replaced,17/02/2010 08:59,195.24,F1/922185,Kings Langley,Abbots Rise,SW,Hempstead Road to house 59,2U415/10
4,1350964,646550,05/02/2008 16:41,CW,CPTH,Pothole In Road,NaN,400,06/02/2008 12:00,The road was repaired at the jucntion of the A...,CSC3,0400-Repaired/Replaced,NaN,NaN,NaN,Kings Langley,Abbots Rise,EH,Hempstead Road to house 59,2U415/10
5,1377901,701625,10/07/2008 12:00,CW,CPTH,Pothole In Road,NaN,410,10/07/2008 14:40,Road surface is breaking up on section of road...,WEB,0410-Fault Made Safe,NaN,NaN,NaN,Kings Langley,Abbots Rise,WEB,Hempstead Road to house 59,2U415/10

In [112]:
df.to_csv(r'C:\Users\J FernandezGomez\Jupyter Notebooks\Cleaning_Data_Notebooks\2_Defects\Defects_consolidate_final.csv')

In [114]:
df.shape

(1114184, 20)